name: Build and Deploy Python CDK app

on: [push]

env:
  FORCE_COLOR: "1"

jobs:
  deploy-serverless-example:
    name: CDK Python Serverless Build/Deploy
    uses: automartin5000/gha-examples/.github/workflows/python_serverless_cdk_deploy.yml@main
    with:
      dir: examples/serverless/