name: Build and Deploy Python CDK app

on: 
  workflow_call:
    inputs:
      dir:
        required: true
        type: string

    secrets:
      aws_access_key_id_build:
        required: true
      aws_secret_key_build:
        required: true
      aws_access_key_id_dev:
        required: true
      aws_secret_key_dev:
        required: true
      aws_access_key_id_prod:
        required: true
      aws_secret_key_prod:
        required: true
      deployment_bucket:
        required: true

env:
  FORCE_COLOR: "1"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      cdk_s3_key: ${{ steps.cdk-upload.outputs.cdk_s3_key }}

    defaults:
      run:
        working-directory: ${{ inputs.dir }}
    environment:
        name: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_build }}
          aws-secret-access-key: ${{ secrets.aws_secret_key_build }}
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Install App Dependencies
        working-directory: ${{ inputs.dir }}/runtime
        run: |
          pip install -r requirements.txt -t .

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install CDK App Dependencies
        working-directory: ${{ inputs.dir }}/infrastructure
        run: |
          pip install -r requirements.txt

      - name: CDK Synth
        working-directory: ${{ inputs.dir }}/infrastructure
        run: |
          cdk synth

      - name: CDK Diff Int
        working-directory: ${{ inputs.dir }}/infrastructure
        run: |
          cdk diff int --app cdk.out

      - name: Upload cdk.out to S3
        id: cdk-upload
        working-directory: ${{ inputs.dir }}/infrastructure
        run: |
          zip -r cdk_out.zip cdk.out/
          CDK_OUT_SHA=$(sha256sum cdk_out.zip | cut -d " " -f 1)
          aws s3 cp \
              cdk_out.zip \
              s3://${{ secrets.deployment_bucket }}/$CDK_OUT_SHA.zip
          echo "::set-output name=cdk_s3_key::$CDK_OUT_SHA.zip"


  deploy_int:
    name: INT Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
        name: int
        url: ${{ steps.cdk_deploy.outputs.app_url }}
    steps:
      - name: Configure AWS Environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_dev }}
          aws-secret-access-key: ${{ secrets.aws_secret_key_dev }}
          aws-region: us-east-1

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Download cdk.out from S3
        env:
          BUCKET: ${{ secrets.deployment_bucket }}
          KEY: ${{ needs.build.outputs.cdk_s3_key }}
        run: |
          aws s3 cp \
              s3://$BUCKET/$KEY \
              cdk.zip
          unzip cdk.zip

      - name: CDK Deploy Int
        id: cdk_deploy
        run: |
          cdk --app cdk.out/ deploy int --require-approval never --outputs-file cdk_deploy_outputs.json
          APP_URL=$(jq -r '.. | objects | to_entries | .[] | select(.key == "AppURL") | .value' cdk_deploy_outputs.json)
          echo "::set-output name=app_url::$APP_URL"

      # TODO: Upload this to somewhere visible
      - name: CDK Diff Prod
        run: |
          cdk diff prod --app cdk.out

      # TODO: Kick off async performance/int testing

  deploy_prod:
    name: PROD Deploy
    runs-on: ubuntu-latest
    needs: deploy_int
    environment:
      name: prod
      url: ${{ steps.cdk_deploy.outputs.app_url }}
    steps:
      - name: Configure AWS Environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_prod }}
          aws-secret-access-key: ${{ secrets.aws_secret_key_prod }}
          aws-region: us-east-1

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Download cdk.out from S3
        env:
          BUCKET: ${{ secrets.deployment_bucket }}
          KEY: ${{ needs.build.outputs.cdk_s3_key }}
        run: |
          aws s3 cp \
              s3://$BUCKET/$KEY \
              cdk.zip
          unzip cdk.zip

      - name: CDK Deploy Prod
        id: cdk_deploy
        run: |
          cdk --app cdk.out/ deploy prod --require-approval never --outputs-file cdk_deploy_outputs.json
          APP_URL=$(jq -r '.. | objects | to_entries | .[] | select(.key == "AppURL") | .value' cdk_deploy_outputs.json)
          echo "::set-output name=app_url::$APP_URL"
            